### ISSUE TITLE
Getting an unhandled System.Reflection.TargetInvocationException

### ISSUE THREAD

**Issue by luisrr1590** [jsuarezruiz/FavFighters#1]
The error is simple....no matter what i do i'm getting an unhandled System.Reflection.TargetInvocationException when the app is loading.

Running on Visual Studio 2017 with the latest API 28 installed.

**Comment by chinni-nag** [comment]
@jsuarezruiz  I tried the same sample in current project Swipe from left to right and right to left working fine. But when i try to execute the command parameter or selection of that one item in list selection is not working . For instance am attaching the screen shot about the issue, below screen shot you can find the 3 dots symbol and small plus icon so those click are not working fine after add swipe view. Please let me know. Thanks.
![Swipeview issue](https://user-images.githubusercontent.com/52288258/74035926-44440880-49e1-11ea-9aaa-242e2bc371b9.png)

**Comment by saamerm** [comment]
@luisrr1590 did you try it on VS 2019?

**Comment by luisrr1590** [comment]
thank you for answering...yes I have tried in vs 2019 and the error dissapeared. Thank you
